### ISSUE TITLE
Entity specific info

### ISSUE THREAD

**Issue by tarasmen** [krismuniz/google-kgsearch#2]
I am currently using your Knowlegde Graph search API in system which is a nice feature.
However I am very interested in the possibility of having it return information such as phone number and address (specific info for entity type as Organisation).
There for Iwant to kindly request that you add that to the API.

**Comment by krismuniz** [comment]
Unfortunately, this library is only a wrapper around the Knowledge Graph Search API provided by Google. All the data returned by the module is what the API returns. 

That said, I recommend using the [Google Places API](https://developers.google.com/places/web-service/details) to get details about a business or organization such as address and phone number!
